name: Upload to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "google-colab/flank_quickstart_colab.ipynb"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Replace with your AWS region

      - name: Upload file to S3
        run: aws s3 cp google-colab/flank_quickstart_colab.ipynb s3://${{ secrets.AWS_BUCKET }}/google-colab/flank_quickstart_colab.ipynb --acl public-read
